# Generate 600-text dataset from `human_200.csv`

Self-contained Databricks notebook.

Uses only **GPT-4.1** via Azure OpenAI REST calls.

No separate stats file is created. The source human texts are used only to compute temporary prompt metadata in memory.

In [0]:
# Fixed Databricks paths
INPUT_PATH = "/Workspace/Users/aza@tembi.io/eip_etl/human_200.csv"
OUTPUT_DIR = "/Workspace/Users/aza@tembi.io/eip_etl"
MODEL_DEPLOYMENT = "gpt-4.1"

AI_PLAIN_PATH = f"{OUTPUT_DIR}/ai_plain_200.csv"
AI_OBFUSCATED_PATH = f"{OUTPUT_DIR}/ai_obfuscated_200.csv"
DATASET_600_PATH = f"{OUTPUT_DIR}/dataset_600.csv"

print("INPUT_PATH:", INPUT_PATH)
print("AI_PLAIN_PATH:", AI_PLAIN_PATH)
print("AI_OBFUSCATED_PATH:", AI_OBFUSCATED_PATH)
print("DATASET_600_PATH:", DATASET_600_PATH)

INPUT_PATH: /Workspace/Users/aza@tembi.io/eip_etl/human_200.csv
AI_PLAIN_PATH: /Workspace/Users/aza@tembi.io/eip_etl/ai_plain_200.csv
AI_OBFUSCATED_PATH: /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
DATASET_600_PATH: /Workspace/Users/aza@tembi.io/eip_etl/dataset_600.csv

In [0]:
%pip install nltk
dbutils.library.restartPython()

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 21.4 MB/s eta 0:00:00
Requirement already satisfied: joblib in /databricks/python3/lib/python3.10/site-packages (from nltk) (1.2.0)
Collecting regex>=2021.8.3
  Downloading regex-2026.5.9-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (794 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 794.1/794.1 kB 74.3 MB/s eta 0:00:00
Requirement already satisfied: click in /databricks/python3/lib/python3.10/site-packages (from nltk) (8.0.4)
Collecting tqdm
  Downloading tqdm-4.68.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 17.9 MB/s eta 0:00:00
Installing collected packages: tqdm, regex, nltk
Successfully installed nltk-3.9.4 regex-2026.5.9 tqdm-4.68.1
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
import re
import time
import string
import requests
import pandas as pd
from collections import Counter
import nltk

nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)
nltk.download("stopwords", quiet=True)

from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.probability import FreqDist
import string

## Load `human_200.csv`

Expected columns: `text`, `genre`, and either `source_idx` or `index`.

In [0]:
human = pd.read_csv(INPUT_PATH)

human = human[["source_idx", "genre", "text"]].copy()
human["label"] = 0
human["obfuscated"] = False
human["model"] = "human"
human["condition"] = "human"

print(human.shape)
print(human["genre"].value_counts(dropna=False))
human.head()

human_200 = human.copy()

(200, 7)
fiction    67
news       67
essays     66
Name: genre, dtype: int64

## Temporary prompt metadata

Used only so GPT sees genre, approximate word count, stylometric stats, and topic keywords.

In [0]:
STOPWORDS = set(stopwords.words("english"))

def get_words(text):
    tokens = word_tokenize(str(text))
    return [
        token.lower()
        for token in tokens
        if any(ch.isalpha() for ch in token)
    ]

def get_sentences(text):
    return sent_tokenize(str(text))

def extract_topic_keywords(text, top_n=8):
    words = get_words(text)

    content_words = [
        word
        for word in words
        if word not in STOPWORDS
        and word not in string.punctuation
        and len(word) > 2
    ]

    freq = FreqDist(content_words)
    return [word for word, _ in freq.most_common(top_n)]

def compute_stats(text):
    text = str(text)

    words = get_words(text)
    sentences = get_sentences(text)

    approx_word_count = len(words)

    avg_sentence_length = (
        approx_word_count / len(sentences)
        if sentences else 0
    )

    avg_word_length = (
        sum(len(word) for word in words) / approx_word_count
        if approx_word_count else 0
    )

    type_token_ratio = (
        len(set(words)) / approx_word_count
        if approx_word_count else 0
    )

    punct_density = (
        sum(1 for char in text if char in string.punctuation) / len(text)
        if text else 0
    )

    return {
        "avg_sentence_length": round(avg_sentence_length, 3),
        "avg_word_length": round(avg_word_length, 3),
        "type_token_ratio": round(type_token_ratio, 3),
        "punct_density": round(punct_density, 4),
        "approx_word_count": approx_word_count,
        "topic_keywords": extract_topic_keywords(text, top_n=8),
    }

stats_rows = []

for _, row in human_200.iterrows():
    stats = compute_stats(row["text"])
    stats_rows.append({
        "source_idx": row["source_idx"],
        "genre": row["genre"],
        "approx_word_count": stats["approx_word_count"],
        "avg_sentence_length": stats["avg_sentence_length"],
        "avg_word_length": stats["avg_word_length"],
        "type_token_ratio": stats["type_token_ratio"],
        "punct_density": stats["punct_density"],
        "topic_keywords": stats["topic_keywords"],
    })

gen_inputs = pd.DataFrame(stats_rows)

gen_inputs.head()

   source_idx  ...                                     topic_keywords
0        1116  ...  [father, land, brother, bastard, son, sir, rob...
1        1368  ...  [thy, thou, edward, warwick, king, richard, ri...
2         422  ...  [clown, titus, emperor, sir, thou, come, shall...
3         413  ...  [marfa, petrovna, avdotya, romanovna, would, f...
4         451  ...  [antony, enobarbus, eros, scarus, enter, like,...

[5 rows x 8 columns]

## GPT-4.1 through Azure OpenAI REST

In [0]:
AOAI_KEY = dbutils.secrets.get("kv-deep-eip-secret", "SERVICES-AZURE-AIFOUNDRY-KEY")
AOAI_ENDPOINT = dbutils.secrets.get("kv-deep-eip-secret", "SERVICES-AZURE-AIFOUNDRY-URL").rstrip("/")
AOAI_VERSION = "2024-10-21"


def call_gpt41(prompt, max_tokens=1000, temperature=0.8, retries=3):
    url = f"{AOAI_ENDPOINT}/openai/deployments/{MODEL_DEPLOYMENT}/chat/completions?api-version={AOAI_VERSION}"
    headers = {
        "api-key": AOAI_KEY,
        "Content-Type": "application/json",
    }
    payload = {
        "messages": [
            {
                "role": "system",
                "content": "You write original English text matching requested genre and constraints. Output plain text only. No markdown. No titles unless explicitly requested.",
            },
            {"role": "user", "content": prompt},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
    }

    last_error = None
    for attempt in range(retries):
        try:
            r = requests.post(url, headers=headers, json=payload, timeout=90)
            if r.status_code == 429 and attempt < retries - 1:
                time.sleep(5 * (attempt + 1))
                continue
            r.raise_for_status()
            body = r.json()
            return body["choices"][0]["message"]["content"].strip()
        except Exception as e:
            last_error = e
            if attempt < retries - 1:
                time.sleep(3 * (attempt + 1))
            else:
                raise last_error

## Prompts

The original human text is never sent to the model.

In [0]:
BANNED_WORDS = [
    "delve", "intricate", "underscore", "meticulous", "testament", "realm", "pivotal",
    "robust", "comprehensive", "seamless", "leverage", "utilize", "nuanced", "multifaceted",
    "tapestry", "embark", "furthermore", "moreover", "notably", "significantly",
]


def feature_block(row):
    return (
        f"Genre: {row['genre']}\n"
        f"Approximate word count: {int(row['approx_word_count'])}\n"
        f"Average sentence length: {row['avg_sentence_length']}\n"
        f"Average word length: {row['avg_word_length']}\n"
        f"Type-token ratio: {row['type_token_ratio']}\n"
        f"Punctuation density: {row['punct_density']}\n"
        f"Topic keywords: {row['topic_keywords']}"
    )


def plain_prompt(row):
    return f"""Write one original {row['genre']} text.

Use the following derived metadata from a human text. Do not ask for or refer to any source text. Do not imitate any specific author or publication. Create a new text that naturally fits the genre, approximate length, style statistics, and topics.

{feature_block(row)}

Requirements:
- Write naturally.
- No markdown.
- No bullet points.
- No title.
- Output text only."""


def obfuscated_prompt(row):
    genre = str(row["genre"]).strip().lower()
    banned = ", ".join(BANNED_WORDS)

    if genre == "fiction":
        technique = "fiction_disfluency_humanized"
        instructions = """Make it sound like a human wrote it casually and imperfectly.
- Add disfluencies, including false starts and self-corrections.
- Include filler phrases such as "the thing is" and "and honestly".
- Include at least two rhetorical questions.
- Use heavy contractions.
- Use wildly varied sentence length."""
    elif genre == "news":
        technique = "translated_news_awkward_plain"
        instructions = """Write as if the text was translated from another language.
- Use slightly awkward phrasing.
- Use plain vocabulary.
- Avoid smooth transitions.
- Prefer short sentences.
- Keep it news-like, but not polished."""
    elif genre == "essays":
        technique = "essay_mixed_lengths_first_person"
        instructions = """Make it sound human and uneven.
- Mix very short sentences under 5 words with long sentences.
- Include a personal first-person anecdote.
- Do not use these phrases: "in conclusion", "furthermore", "moreover", "it is worth noting"."""
    else:
        technique = "generic_humanized"
        instructions = """Make it sound human and uneven.
- Use varied sentence length.
- Include small imperfections in rhythm and phrasing.
- Avoid sounding polished or template-like."""

    prompt = f"""Write one original {row['genre']} text.

Use the following derived metadata from a human text. Do not ask for or refer to any source text. Do not imitate any specific author or publication. Create a new text that fits the genre, approximate length, style statistics, and topics.

{feature_block(row)}

Obfuscation / humanization instructions:
{instructions}

Avoid all of these words and phrases: {banned}.

Requirements:
- No markdown.
- No bullet points.
- No title.
- Output text only."""
    return prompt, technique

## Generate `ai_plain_200.csv`

In [0]:
def load_existing(path):
    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()


def save_csv(df, path):
    df.to_csv(path, index=False)
    print(f"Saved {len(df)} rows -> {path}")


plain_existing = load_existing(AI_PLAIN_PATH)
plain_done = set(plain_existing["source_idx"].tolist()) if not plain_existing.empty and "source_idx" in plain_existing.columns else set()
plain_rows = plain_existing.to_dict("records") if not plain_existing.empty else []

for _, row in gen_inputs.iterrows():
    source_idx = row["source_idx"]
    if source_idx in plain_done:
        continue

    text = call_gpt41(plain_prompt(row), max_tokens=1000, temperature=0.8)
    plain_rows.append({
        "source_idx": source_idx,
        "genre": row["genre"],
        "model": MODEL_DEPLOYMENT,
        "text": text,
        "label": 1,
        "obfuscated": False,
    })
    print(source_idx, text)
    if len(plain_rows) % 10 == 0:
        save_csv(pd.DataFrame(plain_rows), AI_PLAIN_PATH)

ai_plain = pd.DataFrame(plain_rows)
save_csv(ai_plain, AI_PLAIN_PATH)
ai_plain.head()

1116 Jon stood at the far end of the pasture, hands deep in the pockets of his old coat, boots pressing muddy prints into the fresh spring grass. The morning was pale and cold, and the dew on the fence posts shivered in the wind. For a long moment, he watched his father, Sir Robert, checking the stone wall, pressing at loose rocks, shifting his weight from heel to toe as he considered what needed fixing. Robert’s back was broad, bent with age and years of stubbornness, but his voice rang out as clear as ever when he called for his younger son.

“You there, Sam! Check the west corner, the sheep keep getting through. And bring that damn hammer. Can’t do everything myself.”

Jon’s brother, Sam, hurried over, tripping a little in the long grass. Sam had their mother’s nose and their father’s anxious frown, but lacked the weight in his shoulders that Jon bore, the heaviness passed along like a secret between firstborn and father. Jon watched him scramble, the tools jangling at his side, and felt a familiar ache—the twist of affection and envy and something else that had grown sharp since he’d been told, quietly but firmly, to leave school last autumn.

He looked back at the house that sat hunched on the rise, stone and slate and a chimney that always seemed to lean into the wind. He remembered nights sitting at the kitchen table, his father’s hands wrapped around a mug, telling stories of the time before Jon was born, when land was bought and lost, when men stole sheep and fought with knives and bottles in the dark. Sir Robert’s voice always grew soft at the end, the weight of memory making him tired, and Jon would see his mother glance at him, as if to say, this is your inheritance. This is what you get.

Sam reached the fence, knocked a board straight, and looked back over his shoulder. “Hey, Jon, you coming? Or are you just going to stand there all day like a scarecrow?”

Jon shrugged, started the slow walk toward them, boots sinking into mud left by last night’s rain. The land here was always damp, always green, always wanting more care than any one man could give. He thought of his name, the way Sir Robert said it—never with anger but with a roughness, a dryness, as if he were trying to remember something important. Jon had never asked about his older half-brother, the one everyone whispered about, the one whose name was spoken only in arguments and old stories, the bastard son who left for the city and never came back. The land does not remember, his father would say, but sons do.

The morning work went on, the three of them scattered across the field, each lost in their own thoughts. Jon hammered a post back into place, feeling the shock of the wood through his arms, the same stubbornness his father claimed as his own. Sam whistled tunelessly, dropped nails in the grass, and cursed under his breath. Sir Robert moved slower now, but he checked every corner, every stone, never letting his sons see how tired he was.

By noon, the sun had burned off the mist. They sat in the shade of the old oak, passing a worn thermos between them. Sam talked about the village, stories of girls and fights by the river, about who was courting who. Jon listened, only half hearing, watching his father’s face. Sir Robert’s eyes were fixed on the horizon, the line where their land ended and the neighbor’s began. He spoke suddenly, voice low.

“One day, this will be yours, Jon. All of it, if you want it. Or you can go. I won’t stop you.”

Jon didn’t answer. He thought of the land, the weight of it, the love and anger and years packed into every stone and fence post. He thought of his brother, the bastard who left, and wondered where he’d gone and if he had found peace. He looked at Sam, who was laughing at something he’d said, and felt the sharp edge of loyalty and longing.

He turned the thermos in his hands. “It’s hard work,” he said finally.

Sir Robert smiled, tired and proud. “Aye. Only kind worth doing.”

The wind picked up, carrying the smell of earth and old grass. Sam tossed a pebble at Jon’s boot, grinning. Their father stood, dusted off his coat, and headed back to the field. Jon watched him go, feeling the pull of land and blood, of fathers and sons, and stood to follow. The day was not over yet.
1368 The candle guttered, casting tall shadows on the stones. Within the depth of Warwick’s hall, the silence pressed thick as wool upon the men gathered. Richard, youngest scion of the house, turned his eyes to Edward, his brother, and found his gaze steady, unyielding as winter ice. The banners above them, stitched with the lion and the rose, hung limp in the stale air. War had pressed hardship upon them, and none could say when comfort would return.

“Art thou resolved?” Edward’s voice broke the silence, sharp as flint. “Shall we call ourselves brothers still, or foes?”

Richard set his jaw, feeling the pulse in his throat. “Ever thy brother, Edward,” he said, though his heart beat with doubt. “But Warwick hath claim, and his men rally to him. Wilt thou bid me turn traitor to blood?”

Edward’s brow furrowed. He rose, his cloak falling in folds about him. “Nay, Richard,” he said, more softly. “I would only have thee loyal to right. Blood binds us, but so doth our oath to the crown. Warwick’s quarrel is his own; he would set the realm aflame for his pride.”

The candles trembled in a sudden draft of wind. Beyond the window, rain struck the panes, a ceaseless drumming. Richard’s mind drifted to the fields of Towton, where he had seen friends fall in bloody snow, and the cost of war was written in the faces of widows and orphaned sons.

“Wouldst thou have peace?” Richard murmured, not daring to meet his brother’s eyes.

Edward’s fist clenched. “Peace is the wish of all men, but Warwick will not yield. He hath set his banner against mine. The day will come, Richard, when thou must choose—king or kinsman.”

“And if I choose aright?” Richard asked, voice barely above a whisper.

“Then thou art my brother in truth,” Edward said. “And if not, thou must answer to God.”

Richard turned, the weight of that reply pressing upon him. He crossed to the window, looking out at the sodden night. The world beyond was black and formless, yet he saw in it the faces of men who would march at dawn, trusting in his name, expecting justice.

“Dost thou remember our childhood?” Richard asked, not turning. “We hunted in the woods of York, and thought ourselves princes of all we surveyed. What is left of those days, Edward?”

Edward's voice softened. “Only memory, and perhaps regret. Yet kings do not live in memory, brother. Nor can I.”

The door opened, and a servant entered with news. “My lord, Warwick’s men are sighted on the eastern road. They make camp at the ford.”

Edward nodded, dismissing the man with a gesture. The brothers stood together, the silence a gulf between them. Richard knew what must come, but wished with all his soul that it might be otherwise.

“Will thou ride with me?” Edward asked.

“I will,” Richard answered, the words tasting bitter. “For thy cause, and for England.”

Edward smiled, grim and tired. “Then let us pray God finds us in the right.”

As the night waned, the hall emptied, save for the two brothers. Richard lingered as Edward departed, his heart torn. Was right so clear as Edward claimed? Warwick had raised him as a son, and his blood ran in the veins of Richard’s kin. Yet Edward bore the crown, and the law of the land held weight above love.

He slipped from the hall, boots silent on the cold flags. The rain had ceased, but the air was thick with the scent of earth and iron. In the courtyard, men readied their arms, some with laughter, others in silence, each carrying their own measure of fear. Richard mounted his horse, glancing at the sky, where dawn crept pale and uncertain.

The army moved, banners snapping in the wind, armor glinting in the first light. Richard felt the heft of the sword at his side, the burden of choice heavy as stone. As they rode toward the ford, he prayed—for mercy, for wisdom, for the dead who would soon lie upon that field. He prayed for his brother, and for England, torn by men who loved her, and could no longer tell right from pride.

And the river waited, dark and deep, bearing away all that men could not hold.
422 The morning is bright, but the pale, cold light does little to warm the grey stones of the square. Pigeons cluster thick as clouds on the central statue, bobbing and pecking at crumbs left by the night’s last wanderers. The city’s breath is slow as it wakes, but for one man there is never any rest.

Titus sits by the fountain, his thin hands wrapped around his knees, his clothing patched but neat. His face, painted white and red, seems a mask until he smiles—then his eyes crackle with something like fire. He is the emperor’s clown, the fool who is never quite a fool, and the dawn is his time.

He watches an old woman clutch her shawl against the wind. She moves like she is her own shadow, afraid to step in front of herself. As she passes, Titus springs up and bows low, his hat sweeping the stones. “Good morrow, madam!” His voice is bright as a bell.

She starts but manages a smile. “Morrow, sir,” she says, her words soft as wool.

He doffs his hat, and a pigeon feather floats out. He plucks it from the air. “Madam, art thou aware the pigeons plot against us? They speak in code, only the cleverest hear.”

She laughs, surprised at herself. “Do they, sir? And what shall we do?”

Titus leans in, eyes wide. “Trust not the grey ones. Their hearts are thick with secrets. But the white—ah, they are honest, though foolish as myself.”

The woman shakes her head, but holds his gaze a moment longer than she must. “Fools and pigeons, what is the world coming to?” She shuffles on, yet her steps are lighter.

Titus sits back down, his eyes scanning the square. Two city guards march past, speaking in tones meant to be low, but the morning air carries their words.

“Heard the emperor’s ill again?” says the first, rubbing his chin.

“Maybe. They say he calls for his clown in the night,” the second mutters.

Titus grins. “Aye, sirs, thou art right. The emperor sends for me when he cannot sleep! For who better to chase shadows from the royal bed?”

They look at him, one with a sneer, the other uncertain. “Mind thy tongue, fool. Some shadows bite.”

Titus only laughs. “Shall I send my pigeons to guard thee, sir? They’ll coo away all wickedness.”

The guards pass, muttering. Titus is left with the pigeons, who eye him as if he were just another bird, albeit one with a red nose.

A young boy runs into the square, his knees muddy, his eyes wild with wonder. He stares at Titus, standing between the statues’ stone feet. “Are you the emperor’s clown?”

Titus bows low, flourishing his feather. “At your service. Have you come to be jester in my stead?”

The boy giggles, hiding behind his hands. “No, sir. My mother says jesters are for kings, not for boys.”

Titus kneels, so their eyes meet. “Ah, but thou art king of the square this hour. See how the pigeons bow to thee!” He tosses a crumb, and the birds descend in a fluttering wave, wings flashing. The boy laughs, the sound ringing bright.

“Will you show me a trick?” the boy pleads.

Titus considers. “A trick, thou sayest? Watch close, for magic lives in small things.” He hides the feather in his sleeve, then pulls it from behind the boy’s ear.

The boy’s gasp is pure, golden. He claps and claps, and even the oldest pigeon looks on, unimpressed.

A bell tolls in the palace tower. Titus stands, dusts his knees. “Duty calls me, young sir. The emperor needs laughter more than any other man today.”

The boy nods, solemn now. “Are you afraid?”

Titus glances at the palace, looming white and distant. “Aye, sometimes. But jesters wear brave faces, that is our gift.”

The boy watches him go, the pigeons scattering as Titus walks toward the palace gates. The guards wait, faces grim, but Titus greets them like old friends, his hat low and voice light as morning wind.

Inside, corridors twist like the thoughts of men who have seen too much. At the emperor’s door, a servant bows. “He waits for thee. Bring cheer if thou can.”

Titus enters. The emperor sits by the window, pale and tired, the city’s roofs spread before him.

“Come, fool,” the emperor says, his voice a sigh. “Tell me what the pige
413 Marfa Petrovna had always believed, even as a child, that every significant event in her life would be heralded by a sign, a tremor in the air, or a whisper from some hidden corner of her old family house. The windows with their uneven glass reflected the garden where, even in the heart of winter, she often walked alone, hands folded and her thoughts drifting as aimlessly as the snowflakes. Her mother used to call her dreamer and her father, when he was in a good mood, would laugh and ruffle her hair, telling her that no man would know what to do with a girl whose mind wandered so far.

But now, as she sat in the faded blue drawing room, her hands clasped on her lap, she felt not the approach of fate but only the dull ache of expectation. The letter lay on the table before her, open, its neat script and careful words already committed to memory. Avdotya Romanovna was coming to visit, and Marfa could not decide whether she was excited or merely afraid.

It was not their first meeting. They had crossed paths at the governor’s ball the previous winter, when Avdotya, with her dark eyes and quick wit, had drawn everyone to her. Marfa remembered the circle of admirers, the gentle pressure as Avdotya slipped past her, the hint of a smile. Later, as the orchestra played and Marfa wandered out onto the terrace, she had found Avdotya standing alone, a shawl wrapped around her shoulders, her gaze on the moonlit river. They spoke of trivial things, the weather, the latest novels from Petersburg, but beneath the surface there was a current, something unspoken that made Marfa’s heart beat faster.

Since then she had thought of Avdotya more than she cared to admit, her face appearing in Marfa’s dreams, her laughter echoing even in the quietest moments. The letter had arrived unexpectedly, written in Avdotya’s strong, decisive hand, asking if she might come and stay for a few days. Marfa read and reread it, searching for meaning in the ordinary sentences, wondering if Avdotya remembered that night on the terrace, if she too felt something she could not quite name.

The day of Avdotya’s arrival dawned sullen and grey, the garden rimed with frost. Marfa busied herself with preparations, directing the servants, choosing the best room, the tastiest preserves, the softest pillows. When the carriage rolled up the drive and Avdotya stepped out, tall and straight, her cheeks flushed from the cold, Marfa’s heart leapt, and she pressed her hands together tightly.

Their first moments were awkward, both women too aware of the space between them, the polite formalities, the need to say the right thing. But as the hours passed, the old ease returned. They walked in the garden, Avdotya’s laughter bringing color to Marfa’s pale cheeks. They sat late into the evening, speaking of books and hopes, family and disappointments.

One afternoon, as the sun slanted across the parlor, Avdotya told a story of her childhood. Marfa listened, watching the way Avdotya’s hands moved, the way her eyes grew soft with memory. When the story ended, there was a quiet between them that was not uncomfortable. Marfa felt as though something important hovered in the air, ready to be spoken.

“Marfa Petrovna,” Avdotya began, her voice uncharacteristically uncertain. “Do you ever think about how things might have been different if—” She broke off, looking away.

“If we had met sooner?” Marfa asked, trembling.

Avdotya nodded, her fingers twisting the edge of her shawl. “Yes. Perhaps I would not have felt so alone. Perhaps I would have understood myself sooner.”

Marfa’s heart pounded. She reached out, her hand finding Avdotya’s, their fingers entwining with a kind of inevitability. The warmth that flowed between them was unlike anything Marfa had known before.

In the silence that followed, Marfa knew—without need for signs or portent—that her life had changed. She saw in Avdotya’s eyes a reflection of her own longing, her own fear and hope, and realized that sometimes, the first woman you love is the one you have been waiting for all along, without ever daring to give her name.

Outside, snow began to fall again, soft and silent, covering the bare earth with the promise of something unbroken and new. Inside, Marfa and Avdotya sat close together, the world receding to the warm circle of lamplight, the future uncertain but, at last, possible.
451 The room at the top of the palace was open to the sky, its tiled floor cool beneath the feet of anyone brave enough to walk there at dawn. Antony stood by the north-facing balustrade, hands clenched, looking out across the gardens that fell away toward the Nile. The river was barely a shimmer, light drawn up from it in gold and blue. He waited, but he did not know for what.

Enobarbus arrived quietly, his steps steady. He did not speak at first, only came to stand near Antony. They were old friends, but the air was tense, troubled by the night. They watched the city’s rooftops below. Somewhere, far off, a cockerel called.

“You have not slept,” Enobarbus said at last.

Antony shook his head. “Nor have you.”

Enobarbus smiled briefly. “The queen is restless. She summons her poets and dancers, but the night grows longer for it.”

Antony’s answer was a sigh. “She is afraid.”

“All the world is afraid, my lord. The armies gather, and the messengers bring only more news of Octavius.”

Behind them, sandals scraped the stone. Eros entered, his eyes eager, as though he thought he brought good tidings. He bowed low. “Scarus waits below. The men are assembled. He says the day is for you to command.”

Antony’s voice was weary. “Tell Scarus to wait.” He glanced at Enobarbus. “Is there any hope left?”

Eros hesitated, then slipped away.

Enobarbus answered in a low voice. “Hope takes the shape of battle, and the shape is ever-changing. The men believe in you. They believe the queen’s star will rise again.”

Antony turned from the view. The sky was brighter now, the city waking. “When Cleopatra comes, she brings the heat of Egypt with her. But she cannot change the world beyond these palace walls.”

“The world is not yet lost,” Enobarbus said, but even he seemed uncertain.

Their silence was broken by another presence: Scarus himself, bold enough to climb the steps that others feared. His face, scarred and honest, was stubborn with loyalty. “If you mean to fight, we are ready. If you mean to wait, we will wait.”

Antony nodded. “I will come down soon.”

Scarus watched him, searching Antony’s face. “The queen sends word. She wishes to see you.”

Antony looked at the horizon. “Does she come here?”

“No, my lord. She waits in her chamber. There are gifts from the city—bread, wine, jewels. She calls herself queen before all, despite what the Romans say.”

Antony’s laughter was quiet, almost painful. “She will be queen until the world’s last breath.”

Enobarbus put a hand to Antony’s shoulder. “It is not morning yet. The sun delays. There is time for counsel. Let us go to her.”

Antony hesitated, then nodded. Scarus went ahead. Enobarbus lingered, watching Antony. “Do you trust her still?”

Antony’s answer was slow. “I trust the passion in her eyes. I trust nothing else in this world.”

They found Cleopatra in her chamber, draped in silk the color of stormclouds. Her maids hovered, but she waved them away. She stood, tall and proud, her hair coiled like a snake around her head.

She saw Antony and Enobarbus and smiled, but her eyes were tired. “You have come at last. Sit and eat with me. The Romans are not yet at my gates.”

Antony took her hand. “The Romans are never very far.”


   source_idx    genre  ... label obfuscated
0        1116  fiction  ...     1      False
1        1368  fiction  ...     1      False
2         422  fiction  ...     1      False
3         413  fiction  ...     1      False
4         451  fiction  ...     1      False

[5 rows x 6 columns]

## Generate `ai_obfuscated_200.csv`

Safe to rerun: if the file already exists, completed `source_idx` rows are skipped.

In [0]:
obf_existing = load_existing(AI_OBFUSCATED_PATH)
obf_done = set(obf_existing["source_idx"].tolist()) if not obf_existing.empty and "source_idx" in obf_existing.columns else set()
obf_rows = obf_existing.to_dict("records") if not obf_existing.empty else []

for _, row in gen_inputs.iterrows():
    source_idx = row["source_idx"]
    if source_idx in obf_done:
        continue

    prompt, technique = obfuscated_prompt(row)
    text = call_gpt41(prompt, max_tokens=1000, temperature=0.9)
    obf_rows.append({
        "source_idx": source_idx,
        "genre": row["genre"],
        "model": MODEL_DEPLOYMENT,
        "text": text,
        "label": 1,
        "obfuscated": True,
        "technique": technique,
    })

    if len(obf_rows) % 10 == 0:
        save_csv(pd.DataFrame(obf_rows), AI_OBFUSCATED_PATH)

ai_obfuscated = pd.DataFrame(obf_rows)
save_csv(ai_obfuscated, AI_OBFUSCATED_PATH)
ai_obfuscated.head()

Saved 10 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 20 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 30 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 40 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 50 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 60 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 70 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 80 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 90 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 100 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 110 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 120 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 130 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 140 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 150 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 160 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 170 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 180 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 190 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 200 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv
Saved 200 rows -> /Workspace/Users/aza@tembi.io/eip_etl/ai_obfuscated_200.csv

   source_idx    genre  ... obfuscated                     technique
0        1116  fiction  ...       True  fiction_disfluency_humanized
1        1368  fiction  ...       True  fiction_disfluency_humanized
2         422  fiction  ...       True  fiction_disfluency_humanized
3         413  fiction  ...       True  fiction_disfluency_humanized
4         451  fiction  ...       True  fiction_disfluency_humanized

[5 rows x 7 columns]

## Merge into `dataset_600.csv`

Adds `condition` and `doc_id`.

In [0]:
human_out = human[["source_idx", "genre", "model", "text", "label", "obfuscated", "condition"]].copy()
human_out["technique"] = ""

plain_out = pd.read_csv(AI_PLAIN_PATH)
plain_out["condition"] = "ai_plain"
plain_out["technique"] = ""

obf_out = pd.read_csv(AI_OBFUSCATED_PATH)
obf_out["condition"] = "ai_obfuscated"

common_cols = ["source_idx", "genre", "model", "text", "label", "obfuscated", "condition", "technique"]

dataset_600 = pd.concat([
    human_out[common_cols],
    plain_out[common_cols],
    obf_out[common_cols],
], ignore_index=True)

dataset_600["doc_id"] = [f"doc_{i:04d}" for i in range(len(dataset_600))]
dataset_600 = dataset_600[["doc_id"] + common_cols]

save_csv(dataset_600, DATASET_600_PATH)

print(dataset_600.shape)
print(dataset_600["condition"].value_counts())
print(dataset_600.groupby(["condition", "genre"]).size())
dataset_600.head()

Saved 600 rows -> /Workspace/Users/aza@tembi.io/eip_etl/dataset_600.csv
(600, 9)
human            200
ai_plain         200
ai_obfuscated    200
Name: condition, dtype: int64
condition      genre
ai_obfuscated  essays     66
               fiction    67
               news       67
ai_plain       essays     66
               fiction    67
               news       67
human          essays     66
               fiction    67
               news       67
dtype: int64

     doc_id  source_idx    genre  model  ... label  obfuscated  condition technique
0  doc_0000        1116  fiction  human  ...     0       False      human
1  doc_0001        1368  fiction  human  ...     0       False      human
2  doc_0002         422  fiction  human  ...     0       False      human
3  doc_0003         413  fiction  human  ...     0       False      human
4  doc_0004         451  fiction  human  ...     0       False      human

[5 rows x 9 columns]

In [0]:
assert len(dataset_600) == 600, f"Expected 600 rows, got {len(dataset_600)}"
assert dataset_600["doc_id"].is_unique
assert dataset_600["condition"].value_counts().to_dict() == {
    "human": 200,
    "ai_plain": 200,
    "ai_obfuscated": 200,
}
assert set(dataset_600["label"].unique()).issubset({0, 1})
print("All checks passed.")

All checks passed.